/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pkg.mgmt.Utils;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages = { "com.pkg" })
@EnableCaching
public class PackageManagementMain {

	public static void main(String... args) {
		SpringApplication application = new SpringApplication(PackageManagementMain.class);
		application.run(args);

	}

}
